use std::{
    env,
    error::Error,
    fs,
    io::{Error as IoError, ErrorKind},
    path::{Path, PathBuf},
};

use cbindgen::{Builder, Config, DocumentationLength, Language};

fn rustc_path_is_safe(rustc: &str) -> bool {
    if rustc.is_empty() || rustc.len() >= 4_096 {
        return false;
    }

    // Reject shell metacharacters while allowing Windows path separators.
    if rustc.chars().any(|ch| {
        matches!(
            ch,
            ';' | '&'
                | '|'
                | '`'
                | '$'
                | '>'
                | '<'
                | '\n'
                | '\r'
                | '\0'
                | '\t'
                | '"'
                | '\''
                | '*'
                | '?'
                | '['
                | ']'
                | '{'
                | '}'
                | '('
                | ')'
                | '~'
                | '#'
                | '!'
                | '%'
                | '^'
                | ' '
        )
    }) {
        return false;
    }

    let lower = rustc.to_ascii_lowercase();
    if rustc.contains("..") || lower.contains("%2e%2e") || lower.contains("%20") {
        return false;
    }

    if rustc.starts_with('-') {
        return false;
    }

    let is_simple = !rustc.contains('/') && !rustc.contains('\\');
    let bytes = rustc.as_bytes();
    let is_absolute_unix = rustc.starts_with('/');
    let is_absolute_windows = bytes.len() >= 3
        && bytes[0].is_ascii_alphabetic()
        && bytes[1] == b':'
        && matches!(bytes[2], b'/' | b'\\');
    let is_unc = if bytes.len() >= 5 && bytes[0] == b'\\' && bytes[1] == b'\\' {
        let third = bytes[2];
        third != b'\\' && third != b'/' && bytes[2..].contains(&b'\\')
    } else {
        false
    };

    if !(is_simple || is_absolute_unix || is_absolute_windows || is_unc) {
        return false;
    }

    if is_simple && rustc.contains(':') {
        return false;
    }

    if !is_simple {
        let inspected_path = match fs::canonicalize(rustc) {
            Ok(path) => path,
            Err(_) if is_absolute_windows || is_unc => PathBuf::from(rustc),
            Err(_) => return false,
        };

        if let Some(path_str) = inspected_path.to_str() {
            let lower_path = path_str.to_ascii_lowercase();
            if lower_path.contains("..") || lower_path.contains("%2e%2e") {
                return false;
            }
        }

        let file_name = inspected_path
            .file_name()
            .and_then(|name| name.to_str())
            .map(|name| name.to_ascii_lowercase());

        let allowed_wrapper = match file_name.as_deref() {
            Some(name)
                if name == "rustc"
                    || name == "rustc.exe"
                    || name == "sccache"
                    || name == "sccache.exe"
                    || name.contains("rustc") =>
            {
                true
            },
            _ => false,
        };

        if !allowed_wrapper {
            return false;
        }
    }

    true
}

fn main() {
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    if !rustc_path_is_safe(&rustc) {
        panic!("refusing to execute rustc with potentially malicious path: {rustc}");
    }

    if let Err(err) = generate_header() {
        panic!("failed to generate C header: {err}");
    }
}

fn build_config(header_preamble: &str) -> Config {
    Config {
        language: Language::C,
        pragma_once: true,
        cpp_compat: true,
        include_version: true,
        autogen_warning: Some(
            "/* WARNING: This file is autogenerated by cbindgen. Do not edit manually. */"
                .to_string(),
        ),
        header: Some(header_preamble.to_string()),
        documentation: true,
        documentation_length: DocumentationLength::Full,
        ..Config::default()
    }
}

fn generate_header() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=Cargo.toml");

    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let generated_include_dir = out_dir.join("include");

    let header_filename = "majestic_world_ffi.h";
    let out_header_path = generated_include_dir.join(header_filename);
    let crate_include_dir = crate_dir.join("include");
    let header_preamble = r#"/*
 * Majestic World FFI (auto-generated).
 *
 * This header is generated by cbindgen during the Rust build and exposes the
 * `mw_core_*` APIs for consumption from C or Unreal Engine 5 modules.
 *
 * Example usage:
 *
 *     #include <stdio.h>
 *     #include "majestic_world_ffi.h"
 *
 *     int main(void) {
 *         MwCoreConfig config;
 *         MwState *state = NULL;
 *
 *         if (mw_core_config_default(&config) != MwResult_Success) {
 *             fprintf(stderr, "Failed to populate default config.\n");
 *             return 1;
 *         }
 *
 *         if (mw_core_create(&config, &state) != MwResult_Success) {
 *             fprintf(stderr, "Failed to create Majestic World state.\n");
 *             return 1;
 *         }
 *
 *         MwResult tick_result = mw_core_tick(state, 1.0f, 1);
 *         if (tick_result != MwResult_Success) {
 *             fprintf(stderr, "Tick failed: %d\n", (int)tick_result);
 *         }
 *
 *         // Proper cleanup is essential
 *         if (state != NULL) {
 *             mw_core_destroy(state);
 *         }
 *         return tick_result == MwResult_Success ? 0 : 1;
 *     }
 */"#;

    let config = build_config(header_preamble);

    let bindings = Builder::new()
        .with_config(config)
        .with_crate(&crate_dir)
        .generate()
        .map_err(|err| IoError::new(ErrorKind::Other, format!("cbindgen failed: {err}")))?;

    let mut new_file_bytes = Vec::new();
    bindings.write(&mut new_file_bytes);
    let new_contents = String::from_utf8(new_file_bytes).map_err(|err| {
        IoError::new(
            ErrorKind::InvalidData,
            format!("header contained invalid UTF-8: {err}"),
        )
    })?;

    write_if_changed(&out_header_path, &new_contents)?;

    if let Err(err) =
        try_write_repository_header(&crate_include_dir, header_filename, &new_contents)
    {
        let crate_header_path = crate_include_dir.join(header_filename);
        println!(
            "cargo:warning=Failed to update checked-in header copy at {}: {err}",
            crate_header_path.display()
        );
    }

    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != contents,
        Err(err) => match err.kind() {
            ErrorKind::NotFound => true,
            _ => return Err(Box::new(err)),
        },
    };

    if needs_write {
        if let Some(parent) = path.parent() {
            ensure_directory(parent)?;
        }
        fs::write(path, contents)?;
    }

    Ok(())
}

fn ensure_directory(path: &Path) -> Result<(), Box<dyn Error>> {
    if path.exists() {
        if !path.is_dir() {
            return Err(IoError::new(
                ErrorKind::Other,
                format!("Path exists but is not a directory: {}", path.display()),
            )
            .into());
        }
    } else {
        fs::create_dir_all(path)?;
    }

    Ok(())
}

fn try_write_repository_header(
    include_dir: &Path,
    file_name: &str,
    contents: &str,
) -> Result<(), Box<dyn Error>> {
    if !include_dir.exists() {
        return Ok(());
    }

    if !include_dir.is_dir() {
        return Err(IoError::new(
            ErrorKind::Other,
            format!(
                "Include directory path exists but is not a directory: {}",
                include_dir.display()
            ),
        )
        .into());
    }

    let path = include_dir.join(file_name);
    write_if_changed(&path, contents)
}

#[cfg(test)]
mod tests {
    use super::{build_config, rustc_path_is_safe, write_if_changed};
    use std::{
        fs,
        io::{Error as IoError, ErrorKind},
        path::PathBuf,
    };

    struct TempDirGuard(PathBuf);

    impl Drop for TempDirGuard {
        fn drop(&mut self) {
            let path = &self.0;
            let _ = fs::remove_dir_all(path);
        }
    }

    #[test]
    fn accepts_normal_rustc_paths() {
        assert!(rustc_path_is_safe("/usr/bin/rustc"));

        #[cfg(windows)]
        {
            assert!(rustc_path_is_safe("C:/Rust/bin/rustc.exe"));
            assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        }
    }

    #[test]
    fn rejects_paths_with_shell_metacharacters() {
        assert!(!rustc_path_is_safe("/usr/bin/rustc;rm -rf /"));
        assert!(!rustc_path_is_safe("rustc|malicious"));
    }

    #[test]
    fn allows_known_wrappers() {
        assert!(rustc_path_is_safe("/usr/bin/sccache"));
        assert!(rustc_path_is_safe("/usr/local/bin/rustc-wrapper"));
    }

    #[test]
    fn rejects_additional_dangerous_characters() {
        assert!(!rustc_path_is_safe("rustc\0malicious"));
        assert!(!rustc_path_is_safe("rustc\"evil"));
        assert!(!rustc_path_is_safe("rustc'bad'"));
        assert!(!rustc_path_is_safe("rustc\\inject"));
        assert!(!rustc_path_is_safe("rustc*glob"));
        assert!(!rustc_path_is_safe("rustc?wildcard"));
        assert!(!rustc_path_is_safe("rustc[range]"));
        assert!(!rustc_path_is_safe("rustc{expansion}"));
        assert!(!rustc_path_is_safe("rustc(subshell)"));
        assert!(!rustc_path_is_safe("rustc~home"));
        assert!(!rustc_path_is_safe("rustc#fragment"));
        assert!(!rustc_path_is_safe("rustc!history"));
        assert!(!rustc_path_is_safe("rustc%env"));
        assert!(!rustc_path_is_safe("rustc^caret"));
    }

    #[test]
    fn rejects_path_traversal_attempts() {
        assert!(!rustc_path_is_safe("/usr/bin/../../../bin/sh"));
        assert!(!rustc_path_is_safe("../rustc"));
        assert!(!rustc_path_is_safe("rustc/../evil"));
    }

    #[test]
    fn rejects_url_encoded_path_traversal() {
        assert!(!rustc_path_is_safe("/usr/bin/%2e%2e/sh"));
        assert!(!rustc_path_is_safe("%2E%2E/rustc"));
        assert!(!rustc_path_is_safe("rustc/%2e%2E/evil"));
    }

    #[test]
    fn distinguishes_absolute_simple_and_relative_paths() {
        assert!(rustc_path_is_safe("rustc"));
        assert!(rustc_path_is_safe("/usr/bin/rustc"));
        #[cfg(windows)]
        {
            assert!(rustc_path_is_safe("C:/Rust/bin/rustc.exe"));
            assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        }
        assert!(!rustc_path_is_safe("bin/rustc"));
        assert!(!rustc_path_is_safe(".\\rustc.exe"));
    }

    #[cfg(windows)]
    #[test]
    fn accepts_windows_backslash_paths() {
        assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        assert!(rustc_path_is_safe("\\\\server\\share\\rustc.exe"));
    }

    #[test]
    fn rejects_space_characters_and_url_encoded_spaces() {
        assert!(!rustc_path_is_safe("rustc malicious"));
        assert!(!rustc_path_is_safe("/usr/bin/rustc evil"));
        assert!(!rustc_path_is_safe("rustc%20inject"));
        assert!(!rustc_path_is_safe("%20rustc"));
        assert!(!rustc_path_is_safe("rustc%20%20evil"));
    }

    #[test]
    fn rejects_flag_injection() {
        assert!(!rustc_path_is_safe("-Zprint-link-args"));
        assert!(!rustc_path_is_safe("--help"));
    }

    #[test]
    fn rejects_oversized_paths() {
        let oversized = "a".repeat(4_097);
        assert!(!rustc_path_is_safe(&oversized));
    }

    #[test]
    fn config_uses_pragma_once_without_include_guard() {
        let config = build_config("test");
        assert!(config.pragma_once);
        assert!(config.include_guard.is_none());
    }

    #[test]
    fn write_if_changed_propagates_permission_errors() {
        let temp_dir = std::env::temp_dir().join(format!(
            "mw_build_write_permission_test_{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&temp_dir);
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");
        let _guard = TempDirGuard(temp_dir.clone());

        let blocking_path = temp_dir.join("not_a_directory");
        fs::write(&blocking_path, "marker").expect("failed to create blocking file");

        let child_path = blocking_path.join("child.txt");
        let err = write_if_changed(&child_path, "changed").expect_err("write should fail");
        let io_err = err
            .downcast::<IoError>()
            .expect("expected io::Error from write failure");
        assert_eq!(io_err.kind(), ErrorKind::Other);
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_resolving_to_non_rustc() {
        use std::os::unix::fs as unix_fs;

        let temp_dir =
            std::env::temp_dir().join(format!("mw_rustc_symlink_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&temp_dir);
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir for symlink test");
        let _guard = TempDirGuard(temp_dir.clone());

        let malicious_target = temp_dir.join("not_rustc");
        fs::write(&malicious_target, b"#!/bin/sh").expect("failed to create malicious target");

        let symlink_path = temp_dir.join("fake_rustc");
        let _ = fs::remove_file(&symlink_path);
        unix_fs::symlink(&malicious_target, &symlink_path)
            .expect("failed to create symlink for rustc safety test");

        let symlink_str = symlink_path
            .to_str()
            .expect("temp path should be valid UTF-8");
        assert!(!rustc_path_is_safe(symlink_str));
    }

    #[test]
    fn rejects_suspicious_canonical_paths() {
        assert!(!rustc_path_is_safe("/tmp/../../../bin/sh"));
    }
}
