use std::{
    env,
    error::Error,
    fs,
    io::{Error as IoError, ErrorKind},
    path::{Component, Path, PathBuf},
};

use cbindgen::{Builder, Config, DocumentationLength, Language};

const HEADER_FILENAME: &str = "majestic_world_ffi.h";
const HEADER_PREAMBLE_TEMPLATE: &str = r#"/*
 * Majestic World FFI (auto-generated).
 *
 * This header is generated by cbindgen during the Rust build and exposes the
 * `mw_core_*` APIs for consumption from C or Unreal Engine 5 modules. The
 * generated bindings are compatible with UE5.6's bindless resource model,
 * descriptor arrays, and deferred texturing pipeline. They are designed to
 * integrate cleanly with Nanite, Lumen, and ray-tracing passes while
 * preserving deterministic simulation semantics across GPU-driven frames.
 * When targeting large-scale streaming worlds, prefer batching descriptor
 * updates and reuse registered buffers to minimise bindless heap churn.
 *
 * The output filename defaults to "{{HEADER_FILENAME}}" but can be overridden
 * via the MW_FFI_HEADER_NAME environment variable during the Rust build step.
 *
 * Example usage:
 *
 *     #include <stdio.h>
 *     #include <stdlib.h>
 *     #include "{{HEADER_FILENAME}}"
 *
 *     int main(void) {
 *         MwCoreConfig config;
 *         MwState *state = NULL;
 *         MwResult result = MwResult_Success;
 *         int exit_code = EXIT_SUCCESS;
 *
 *         result = mw_core_config_default(&config);
 *         if (result != MwResult_Success) {
 *             fprintf(stderr, "Failed to populate default config: %d\n", (int)result);
 *             exit_code = EXIT_FAILURE;
 *             goto cleanup;
 *         }
 *
 *         result = mw_core_create(&config, &state);
 *         if (result != MwResult_Success) {
 *             fprintf(stderr, "Failed to create Majestic World state: %d\n", (int)result);
 *             exit_code = EXIT_FAILURE;
 *             goto cleanup;
 *         }
 *
 *         result = mw_core_tick(state, 1.0f, 1);
 *         if (result != MwResult_Success) {
 *             fprintf(stderr, "Tick failed: %d\n", (int)result);
 *             exit_code = EXIT_FAILURE;
 *         }
 *
 *     cleanup:
 *         if (state != NULL) {
 *             mw_core_destroy(state);
 *         }
 *         return exit_code;
 *     }
 */"#;

fn get_header_filename() -> String {
    const ENV_KEY: &str = "MW_FFI_HEADER_NAME";
    match env::var(ENV_KEY) {
        Ok(value) => {
            let trimmed = value.trim();
            if trimmed.is_empty() {
                return HEADER_FILENAME.to_string();
            }

            let has_separator = trimmed.contains('/') || trimmed.contains('\\');
            let has_h_extension = trimmed
                .rsplit_once('.')
                .map(|(_, ext)| ext.eq_ignore_ascii_case("h"))
                .unwrap_or(false);

            if has_separator || !has_h_extension {
                println!(
                    "cargo:warning=Ignored {ENV_KEY} value \"{trimmed}\": provide a bare filename \
                     ending in .h"
                );
                return HEADER_FILENAME.to_string();
            }

            trimmed.to_string()
        },
        Err(_) => HEADER_FILENAME.to_string(),
    }
}

fn decode_hex_digit(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

fn contains_forbidden_percent_encoding(value: &str) -> bool {
    let bytes = value.as_bytes();
    let mut index = 0;

    while index + 2 < bytes.len() {
        if bytes[index] != b'%' {
            index += 1;
            continue;
        }

        let high = match decode_hex_digit(bytes[index + 1]) {
            Some(value) => value,
            None => return true,
        };
        let low = match decode_hex_digit(bytes[index + 2]) {
            Some(value) => value,
            None => return true,
        };
        let decoded = (high << 4) | low;

        match decoded {
            b'.' | b'/' | b'\\' | b' ' | b'\t' | b'\n' | b'\r' => return true,
            _ => {},
        }

        index += 3;
    }

    false
}

fn is_allowed_compiler_name(value: &str) -> bool {
    let lower = value.to_ascii_lowercase();

    matches!(
        lower.as_str(),
        "rustc"
            | "rustc.exe"
            | "rustc.bat"
            | "rustc.cmd"
            | "rustc_driver"
            | "rustc_driver.exe"
            | "rustc-wrapper"
            | "rustc-wrapper.exe"
            | "sccache"
            | "sccache.exe"
            | "ccache"
            | "ccache.exe"
    ) || lower.starts_with("rustc-")
        || lower.starts_with("rustc_")
}

// NOTE: We validate both the raw path string and the canonicalised filesystem
// location to defend against obvious traversal attacks (including symlink
// chains) while still delegating race-condition handling to the actual `rustc`
// invocation.
fn rustc_path_is_safe(rustc: &str) -> bool {
    if rustc.is_empty() || rustc.len() >= 4_096 {
        return false;
    }

    // Reject shell metacharacters while allowing Windows path separators.
    if rustc.chars().any(|ch| {
        matches!(
            ch,
            ';' | '&'
                | '|'
                | '`'
                | '$'
                | '>'
                | '<'
                | '\n'
                | '\r'
                | '\0'
                | '\t'
                | '"'
                | '\''
                | '*'
                | '?'
                | '['
                | ']'
                | '{'
                | '}'
                | '('
                | ')'
                | '~'
                | '#'
                | '!'
                | '%'
                | '^'
                | ' '
        )
    }) {
        return false;
    }

    if rustc.contains("..") || contains_forbidden_percent_encoding(rustc) {
        return false;
    }

    if rustc.starts_with('-') {
        return false;
    }

    let path = Path::new(rustc);
    if path
        .components()
        .any(|component| matches!(component, Component::ParentDir | Component::CurDir))
    {
        return false;
    }

    let is_simple = !rustc.contains('/') && !rustc.contains('\\');
    let bytes = rustc.as_bytes();
    let is_absolute_unix = rustc.starts_with('/');
    let is_absolute_windows = bytes.len() >= 3
        && bytes[0].is_ascii_alphabetic()
        && bytes[1] == b':'
        && matches!(bytes[2], b'/' | b'\\');
    let is_unc = if bytes.len() >= 5 && bytes[0] == b'\\' && bytes[1] == b'\\' {
        let third = bytes[2];
        third != b'\\' && third != b'/' && bytes[2..].contains(&b'\\')
    } else {
        false
    };

    if !(is_simple || is_absolute_unix || is_absolute_windows || is_unc) {
        return false;
    }

    if is_simple && rustc.contains(':') {
        return false;
    }

    if is_simple {
        return is_allowed_compiler_name(rustc);
    }

    let inspected_path = match fs::canonicalize(path) {
        Ok(path) => path,
        Err(_) => return false,
    };

    let file_name = inspected_path
        .file_name()
        .and_then(|name| name.to_str())
        .map(|name| name.to_ascii_lowercase());

    match file_name.as_deref() {
        Some(name) if is_allowed_compiler_name(name) => {},
        _ => return false,
    }

    match fs::metadata(&inspected_path) {
        Ok(metadata) if metadata.is_file() => {},
        _ => return false,
    }

    true
}

fn main() {
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    if !rustc_path_is_safe(&rustc) {
        panic!("refusing to execute rustc with potentially malicious path: {rustc}");
    }

    if let Err(err) = generate_header() {
        panic!("failed to generate C header: {err}");
    }
}

fn build_config(header_preamble: &str) -> Config {
    Config {
        language: Language::C,
        pragma_once: true,
        include_guard: None,
        cpp_compat: true,
        include_version: true,
        autogen_warning: Some(
            "/* WARNING: This file is autogenerated by cbindgen. Do not edit manually. */"
                .to_string(),
        ),
        header: Some(header_preamble.to_string()),
        documentation: true,
        documentation_length: DocumentationLength::Full,
        ..Config::default()
    }
}

fn emit_rerun_directives(crate_dir: &Path) -> Result<(), Box<dyn Error>> {
    let build_script = crate_dir.join("build.rs");
    println!("cargo:rerun-if-changed={}", build_script.display());

    let manifest = crate_dir.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", manifest.display());

    emit_rerun_for_sources(&crate_dir.join("src"))?;

    Ok(())
}

fn emit_rerun_for_sources(src_dir: &Path) -> Result<(), Box<dyn Error>> {
    if !src_dir.exists() {
        return Ok(());
    }

    let mut stack = vec![src_dir.to_path_buf()];
    let mut files = Vec::new();

    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            if entry.file_type()?.is_dir() {
                stack.push(path);
            } else if path.extension().map_or(false, |ext| ext == "rs") {
                files.push(path);
            }
        }
    }

    files.sort();
    for file in files {
        println!("cargo:rerun-if-changed={}", file.display());
    }

    Ok(())
}

fn generate_header() -> Result<(), Box<dyn Error>> {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    emit_rerun_directives(&crate_dir)?;

    let cbindgen_toml = crate_dir.join("cbindgen.toml");
    if cbindgen_toml.exists() {
        println!("cargo:rerun-if-changed={}", cbindgen_toml.display());
        // Example cbindgen.toml options for UE integration:
        //   language = "C"
        //   include_guard = "MAJESTIC_WORLD_FFI_H"
        //   pragma_once = true
        //   documentation = true
        //   include_version = true
        // Consider enabling `namespaces` or `cpp_compat` when targeting UE
        // modules that mix C and C++ translation units.
    }

    let header_filename = get_header_filename();

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let generated_include_dir = out_dir.join("include");

    let out_header_path = generated_include_dir.join(&header_filename);
    let crate_include_dir = crate_dir.join("include");
    let header_preamble = HEADER_PREAMBLE_TEMPLATE.replace("{{HEADER_FILENAME}}", &header_filename);

    let config = build_config(&header_preamble);

    let bindings = Builder::new()
        .with_config(config)
        .with_crate(&crate_dir)
        .generate()
        .map_err(|err| -> Box<dyn Error> {
            Box::new(IoError::new(
                ErrorKind::Other,
                format!("cbindgen failed to generate bindings: {err}"),
            ))
        })?;

    let mut new_file_bytes = Vec::new();
    bindings.write(&mut new_file_bytes);

    if new_file_bytes.is_empty() {
        return Err(IoError::new(
            ErrorKind::Other,
            "cbindgen produced an empty header; ensure FFI exports are marked #[no_mangle] and \
             declared extern \"C\"",
        )
        .into());
    }
    let new_contents = String::from_utf8(new_file_bytes)?;
    if new_contents.trim().is_empty() {
        return Err(IoError::new(
            ErrorKind::Other,
            "cbindgen produced an empty header; ensure FFI exports are marked #[no_mangle] and \
             declared extern \"C\"",
        )
        .into());
    }

    write_if_changed(&out_header_path, &new_contents)?;

    if let Err(err) =
        try_write_repository_header(&crate_include_dir, &header_filename, &new_contents)
    {
        let crate_header_path = crate_include_dir.join(&header_filename);
        println!(
            "cargo:warning=Failed to mirror generated header to {}: {err}. Ensure the include/ \
             directory exists and is writable, or set MW_FFI_HEADER_NAME to point UE5 to the \
             OUT_DIR copy at {}.",
            crate_header_path.display(),
            out_header_path.display()
        );
    }

    Ok(())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), Box<dyn Error>> {
    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != contents,
        Err(err) => {
            if err.kind() == ErrorKind::NotFound {
                true
            } else {
                return Err(IoError::new(
                    err.kind(),
                    format!("failed to read existing file {}: {err}", path.display()),
                )
                .into());
            }
        },
    };

    if needs_write {
        if let Some(parent) = path.parent() {
            ensure_directory(parent)?;
        }
        fs::write(path, contents)?;
    }

    Ok(())
}

fn ensure_directory(path: &Path) -> Result<(), Box<dyn Error>> {
    if path.exists() {
        if !path.is_dir() {
            return Err(IoError::new(
                ErrorKind::Other,
                format!("Path exists but is not a directory: {}", path.display()),
            )
            .into());
        }
    } else {
        fs::create_dir_all(path)?;
    }

    Ok(())
}

fn try_write_repository_header(
    include_dir: &Path,
    file_name: &str,
    contents: &str,
) -> Result<(), Box<dyn Error>> {
    if !include_dir.exists() {
        return Ok(());
    }

    let path = include_dir.join(file_name);
    write_if_changed(&path, contents)
}

#[cfg(test)]
mod tests {
    use super::{
        HEADER_FILENAME, build_config, get_header_filename, rustc_path_is_safe, write_if_changed,
    };
    use std::{
        env, fs,
        io::{Error as IoError, ErrorKind},
        path::PathBuf,
    };

    struct TempDirGuard(PathBuf);

    impl Drop for TempDirGuard {
        fn drop(&mut self) {
            let path = &self.0;
            if let Err(err) = fs::remove_dir_all(path) {
                eprintln!(
                    "warning: failed to clean temporary directory {}: {err}",
                    path.display()
                );
            }
        }
    }

    #[test]
    fn accepts_normal_rustc_paths() {
        assert!(rustc_path_is_safe("/usr/bin/rustc"));

        #[cfg(windows)]
        {
            assert!(rustc_path_is_safe("C:/Rust/bin/rustc.exe"));
            assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        }
    }

    #[test]
    fn rejects_paths_with_shell_metacharacters() {
        assert!(!rustc_path_is_safe("/usr/bin/rustc;rm -rf /"));
        assert!(!rustc_path_is_safe("rustc|malicious"));
    }

    #[test]
    fn allows_common_wrappers() {
        assert!(rustc_path_is_safe("/usr/bin/sccache"));
        assert!(rustc_path_is_safe("/usr/local/bin/rustc-wrapper"));
        assert!(rustc_path_is_safe("ccache"));
    }

    #[test]
    fn rejects_additional_dangerous_characters() {
        assert!(!rustc_path_is_safe("rustc\0malicious"));
        assert!(!rustc_path_is_safe("rustc\"evil"));
        assert!(!rustc_path_is_safe("rustc'bad'"));
        assert!(!rustc_path_is_safe("rustc\\inject"));
        assert!(!rustc_path_is_safe("rustc*glob"));
        assert!(!rustc_path_is_safe("rustc?wildcard"));
        assert!(!rustc_path_is_safe("rustc[range]"));
        assert!(!rustc_path_is_safe("rustc{expansion}"));
        assert!(!rustc_path_is_safe("rustc(subshell)"));
        assert!(!rustc_path_is_safe("rustc~home"));
        assert!(!rustc_path_is_safe("rustc#fragment"));
        assert!(!rustc_path_is_safe("rustc!history"));
        assert!(!rustc_path_is_safe("rustc%env"));
        assert!(!rustc_path_is_safe("rustc^caret"));
    }

    #[test]
    fn rejects_path_traversal_attempts() {
        assert!(!rustc_path_is_safe("/usr/bin/../../../bin/sh"));
        assert!(!rustc_path_is_safe("../rustc"));
        assert!(!rustc_path_is_safe("rustc/../evil"));
    }

    #[test]
    fn rejects_url_encoded_path_traversal() {
        assert!(!rustc_path_is_safe("/usr/bin/%2e%2e/sh"));
        assert!(!rustc_path_is_safe("%2E%2E/rustc"));
        assert!(!rustc_path_is_safe("rustc/%2e%2E/evil"));
        assert!(!rustc_path_is_safe("/usr%2e%2e/bin/sh"));
        assert!(!rustc_path_is_safe("path/to/..%2f../evil"));
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_pointing_to_unexpected_binary() {
        use std::os::unix::fs::symlink;

        let temp_dir =
            std::env::temp_dir().join(format!("mw_build_symlink_test_{}", std::process::id()));
        let _ = fs::remove_dir_all(&temp_dir);
        fs::create_dir_all(&temp_dir).expect("failed to create symlink test dir");
        let _guard = TempDirGuard(temp_dir.clone());

        let target = temp_dir.join("not_rustc");
        fs::write(&target, b"echo not rustc").expect("failed to create target file");
        let link_path = temp_dir.join("rustc");
        symlink(&target, &link_path).expect("failed to create symlink");

        let link_str = link_path
            .to_str()
            .expect("symlink path not valid UTF-8")
            .to_string();
        assert!(!rustc_path_is_safe(&link_str));
    }

    #[test]
    fn distinguishes_absolute_simple_and_relative_paths() {
        assert!(rustc_path_is_safe("rustc"));
        assert!(rustc_path_is_safe("/usr/bin/rustc"));
        #[cfg(windows)]
        {
            assert!(rustc_path_is_safe("C:/Rust/bin/rustc.exe"));
            assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        }
        assert!(!rustc_path_is_safe("bin/rustc"));
        assert!(!rustc_path_is_safe(".\\rustc.exe"));
    }

    #[cfg(windows)]
    #[test]
    fn accepts_windows_backslash_paths() {
        assert!(rustc_path_is_safe("C:\\Rust\\bin\\rustc.exe"));
        assert!(rustc_path_is_safe("\\\\server\\share\\rustc.exe"));
    }

    #[test]
    fn rejects_space_characters_and_url_encoded_spaces() {
        assert!(!rustc_path_is_safe("rustc malicious"));
        assert!(!rustc_path_is_safe("/usr/bin/rustc evil"));
        assert!(!rustc_path_is_safe("rustc%20inject"));
        assert!(!rustc_path_is_safe("%20rustc"));
        assert!(!rustc_path_is_safe("rustc%20%20evil"));
    }

    #[test]
    fn rejects_flag_injection() {
        assert!(!rustc_path_is_safe("-Zprint-link-args"));
        assert!(!rustc_path_is_safe("--help"));
    }

    #[test]
    fn rejects_oversized_paths() {
        let oversized = "a".repeat(4_097);
        assert!(!rustc_path_is_safe(&oversized));
    }

    #[test]
    fn config_uses_pragma_once_without_include_guard() {
        let config = build_config("test");
        assert!(config.pragma_once);
        assert!(config.include_guard.is_none());
    }

    #[test]
    fn cbindgen_config_triggers_rebuild_if_present() {
        let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let cbindgen_toml = crate_dir.join("cbindgen.toml");
        if cbindgen_toml.exists() {
            assert!(cbindgen_toml.is_file());
        }
    }

    #[test]
    fn header_filename_respects_env_var() {
        const KEY: &str = "MW_FFI_HEADER_NAME";
        let original = env::var(KEY).ok();

        env::remove_var(KEY);
        assert_eq!(get_header_filename(), HEADER_FILENAME);

        env::set_var(KEY, "custom_ffi.h");
        assert_eq!(get_header_filename(), "custom_ffi.h");

        match original {
            Some(value) => env::set_var(KEY, value),
            None => env::remove_var(KEY),
        }
    }

    #[test]
    fn header_filename_validates_format() {
        const KEY: &str = "MW_FFI_HEADER_NAME";
        let original = env::var(KEY).ok();

        env::set_var(KEY, "invalid_name");
        assert_eq!(get_header_filename(), HEADER_FILENAME);

        env::set_var(KEY, "../evil.h");
        assert_eq!(get_header_filename(), HEADER_FILENAME);

        env::set_var(KEY, "custom.h");
        assert_eq!(get_header_filename(), "custom.h");

        match original {
            Some(value) => env::set_var(KEY, value),
            None => env::remove_var(KEY),
        }
    }

    #[test]
    fn write_if_changed_propagates_permission_errors() {
        let temp_dir = std::env::temp_dir().join(format!(
            "mw_build_write_permission_test_{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&temp_dir);
        fs::create_dir_all(&temp_dir).expect("failed to create temp dir");
        let _guard = TempDirGuard(temp_dir.clone());

        let blocking_path = temp_dir.join("not_a_directory");
        fs::write(&blocking_path, "marker").expect("failed to create blocking file");

        let child_path = blocking_path.join("child.txt");
        let err = write_if_changed(&child_path, "changed").expect_err("write should fail");
        let io_err = err
            .downcast::<IoError>()
            .expect("expected io::Error from write failure");
        assert_eq!(io_err.kind(), ErrorKind::Other);
    }

    #[test]
    fn rejects_suspicious_canonical_paths() {
        assert!(!rustc_path_is_safe("/tmp/../../../bin/sh"));
    }
}
