---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # abort if build exceeds 30 minutes
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2025-09-14
          override: true
      - name: Install Git LFS and verify assets
        run: |
          git lfs install --local
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id || true
          git lfs pull
          git lfs ls-files -l | cut -d' ' -f1 | sort \
            > .lfs-assets-id-pulled || true
          if [ -s .lfs-assets-id ]; then
            diff .lfs-assets-id .lfs-assets-id-pulled
          fi
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install rust components
        run: rustup component add rustfmt clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: |
          cargo clippy \
            --workspace \
            --all-targets \
            --exclude veloren-world \
            -- -D warnings

      - name: Cache advisory DB
        uses: actions/cache@v3
        with:
          path: ~/.cargo/advisory-dbs
          key: ${{ runner.os }}-advisorydb-${{ hashFiles('deny.toml') }}

      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check
          arguments: "--all-features advisories bans licenses sources"

      - name: Test
        run: cargo test --workspace --exclude veloren-world --locked
