---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: nightly-2025-09-14
      - name: Install Git LFS and verify assets
        run: |
          git lfs install --local
          git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id || true
          git lfs pull
          git lfs ls-files -l | cut -d' ' -f1 | sort \
            > .lfs-assets-id-pulled || true
          if [ -s .lfs-assets-id ]; then
            diff .lfs-assets-id .lfs-assets-id-pulled
          fi
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install rust components
        run: rustup component add rustfmt clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: >
          cargo clippy --workspace --all-targets --all-features --
          -D warnings
      - name: Test
        run: cargo test --workspace --all-features
